spring:
  r2dbc:
    url: r2dbc:mysql://database:3306/gorun?tlsVersion=TLSv1.2
    username: user
    password: password
sql:
  init:
    enabled: true
    ddl:
      filepath: sql/schema.sql
    dml:
      filepath: sql/data.sql
