server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: gorun-server

file:
  root-path: ${user.dir}\\codes

snippet:
  file-path: snippets.json

run:
  timeout-ms: 30000L
  timeout-check-time-interval-ms: 100L