spring:
  r2dbc:
    url: r2dbc:h2:file:///devdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false