server:
  error:
    whitelabel:
      enabled: false

file:
  root-path: ${user.dir}\\codes

file-service:
  path:
log-service:
  log-count: 50
code-run-service.max-time-second: 30

snippet:
  file-path: snippets.json



