server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: gorun-server

file:
  root-path: ${user.dir}\\codes

snippet:
  file-path: snippets.json

run:
  url: /run
  timeout: 30s
  timeout-check: 100
