spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/gorun
    username: user
    password: password
sql:
  init:
    enabled: true
    ddl:
      filepath: sql/schema.sql
    dml:
      filepath: sql/data.sql
