version: '3.9'

services:
  server:
    build: .
    container_name: gorun-server
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - gorun
  database:
    image: mysql:5.7
    container_name: gorun-mysql-database
    hostname: database
    environment:
      MYSQL_DATABASE: 'gorun'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - gorun

networks:
  gorun:
    driver: bridge
    external: false
